'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { loadWebData, WebData } from '@/app/lib/data';

export default function DailyPulseCard() {
  const [data, setData] = useState<WebData | null>(null);

  useEffect(() => {
    loadWebData().then(setData).catch(() => {});
  }, []);

  return (
    <Link href="/research/today">
      <div className="bg-[#141414] border border-white/[0.08] rounded-xl p-8 hover:border-[#ff4d4d]/40 transition cursor-pointer group">
        <div className="flex items-center justify-between gap-8 flex-wrap">
          <div className="flex-1 min-w-[300px]">
            <div className="flex items-center gap-3 text-xs uppercase tracking-widest text-[#7cc943] mb-3">
              <span className="w-1.5 h-1.5 bg-[#7cc943] rounded-full animate-pulse"
                    style={{ boxShadow: '0 0 8px rgba(124,201,67,0.5)' }} />
              <span>Live · Updated daily</span>
            </div>
            <h3 className="font-serif text-3xl mb-2">Today&apos;s Thesis</h3>
            <p className="text-[#a1a1a1] text-sm leading-relaxed max-w-xl">
              Auto-generated by the macro and technical agents. Regime classification, asset signals, key indicators, and what would invalidate the thesis.
            </p>
          </div>
          <div className="text-right">
            <div className="text-xs text-[#6b6b6b] mb-2 uppercase tracking-wider">Current Regime</div>
            <div className="font-serif text-2xl text-[#ff4d4d] italic">
              {data?.regimen.clasificacion || '—'}
            </div>
            <div className="text-xs text-[#a1a1a1] mt-1">
              {data?.regimen.confianza || 0}% confidence
            </div>
          </div>
        </div>
        <div className="mt-6 text-xs text-[#6b6b6b] group-hover:text-[#ff4d4d] transition">
          Read today&apos;s pulse →
        </div>
      </div>
    </Link>
  );
}
